# Edit movie context

In [1]:
import pandas as pd
import json

In [2]:
# depth of this file in the project
file_depth = '../../..'

In [3]:
with open(file_depth + '/config/data_25m_config.json') as config_file:
    config = json.load(config_file)

In [4]:
new_context_path = config['new_context_path']
movies_with_context = pd.read_csv(file_depth + new_context_path + 'backup/movies_with_context.csv', encoding="UTF-8")
movies_with_context

,movieId,title,genres,movieYear,titleType,isAdult,runtimeMinutes,directors,writers,actor
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,movie,0,81,nm0005124,"nm0005124,nm0230032,nm0004056,nm0710020,nm0923...","nm0000741,nm0001652,nm0001815,nm0029460,nm0039..."
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,movie,0,104,nm0002653,"nm0378144,nm0852430,nm0833164,nm0885575","nm0001372,nm0001564,nm0002123,nm0003742,nm0051..."
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,movie,0,101,nm0222043,nm0425756,"nm0025908,nm0132587,nm0153170,nm0160648,nm0263..."
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,movie,0,124,nm0001845,"nm0573334,nm0060103","nm0001365,nm0005375,nm0119698,nm0171213,nm0176..."
4,5,Father of the Bride Part II (1995),Comedy,1995,movie,0,106,nm0796124,"nm0352443,nm0329304,nm0583600,nm0796124","nm0003028,nm0015233,nm0030926,nm0042963,nm0056..."
...,...,...,...,...,...,...,...,...,...,...
62290,209157,We (2018),Drama,2018,movie,0,100,nm1415482,"nm1415482,nm1818234","nm10312234,nm11039405,nm1963018,nm3760035,nm42..."
62291,209159,Window of the Soul (2001),Documentary,2001,movie,0,73,"nm0142504,nm1065588","nm0142504,nm1065588",nm1546270
62292,209163,Bad Poems (2018),Comedy|Drama,2018,movie,0,97,nm2520391,nm2520391,"nm0468514,nm0598406,nm10676258,nm1387171,nm158..."
62293,209169,A Girl Thing (2001),Comedy|Drama|Romance,2001,tvMovie,0,237,nm0003022,nm0003022,"nm0121700,nm0453858,nm0841512"
62294,209171,Women of Devil's Island (1962),Action|Adventure|Drama,1962,movie,0,86,nm0659992,"nm0002759,nm0659992","nm0033980,nm0068952,nm0079066,nm0217377,nm0681..."

### Remove writers column

In [5]:
movies_with_context.drop('writers', axis=1, inplace=True)
movies_with_context

,movieId,title,genres,movieYear,titleType,isAdult,runtimeMinutes,directors,actor
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,movie,0,81,nm0005124,"nm0000741,nm0001652,nm0001815,nm0029460,nm0039..."
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,movie,0,104,nm0002653,"nm0001372,nm0001564,nm0002123,nm0003742,nm0051..."
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,movie,0,101,nm0222043,"nm0025908,nm0132587,nm0153170,nm0160648,nm0263..."
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,movie,0,124,nm0001845,"nm0001365,nm0005375,nm0119698,nm0171213,nm0176..."
4,5,Father of the Bride Part II (1995),Comedy,1995,movie,0,106,nm0796124,"nm0003028,nm0015233,nm0030926,nm0042963,nm0056..."
...,...,...,...,...,...,...,...,...,...
62290,209157,We (2018),Drama,2018,movie,0,100,nm1415482,"nm10312234,nm11039405,nm1963018,nm3760035,nm42..."
62291,209159,Window of the Soul (2001),Documentary,2001,movie,0,73,"nm0142504,nm1065588",nm1546270
62292,209163,Bad Poems (2018),Comedy|Drama,2018,movie,0,97,nm2520391,"nm0468514,nm0598406,nm10676258,nm1387171,nm158..."
62293,209169,A Girl Thing (2001),Comedy|Drama|Romance,2001,tvMovie,0,237,nm0003022,"nm0121700,nm0453858,nm0841512"
62294,209171,Women of Devil's Island (1962),Action|Adventure|Drama,1962,movie,0,86,nm0659992,"nm0033980,nm0068952,nm0079066,nm0217377,nm0681..."

### In columns director and actor, keep only the first ID

In [6]:
def keep_first_id(cell):
    if ',' in cell:
        return cell.split(',')[0].strip()
    else:
        return cell.strip()
    
movies_with_context['directors'] = movies_with_context['directors'].apply(keep_first_id)
movies_with_context['actor'] = movies_with_context['actor'].apply(keep_first_id)
movies_with_context

,movieId,title,genres,movieYear,titleType,isAdult,runtimeMinutes,directors,actor
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,movie,0,81,nm0005124,nm0000741
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,movie,0,104,nm0002653,nm0001372
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,movie,0,101,nm0222043,nm0025908
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,movie,0,124,nm0001845,nm0001365
4,5,Father of the Bride Part II (1995),Comedy,1995,movie,0,106,nm0796124,nm0003028
...,...,...,...,...,...,...,...,...,...
62290,209157,We (2018),Drama,2018,movie,0,100,nm1415482,nm10312234
62291,209159,Window of the Soul (2001),Documentary,2001,movie,0,73,nm0142504,nm1546270
62292,209163,Bad Poems (2018),Comedy|Drama,2018,movie,0,97,nm2520391,nm0468514
62293,209169,A Girl Thing (2001),Comedy|Drama|Romance,2001,tvMovie,0,237,nm0003022,nm0121700
62294,209171,Women of Devil's Island (1962),Action|Adventure|Drama,1962,movie,0,86,nm0659992,nm0033980

### One-hot encode movie genres

In [15]:
genres = movies_with_context['genres'].str.lower().str.get_dummies('|')
genres.columns = genres.columns.str.capitalize()
genres = genres.add_prefix('genre')
genres

,genreAction,genreAdult,genreAdventure,genreAnimation,genreBiography,genreChildren,genreComedy,genreCrime,genreDocumentary,genreDrama,...,genreMystery,genreNews,genreReality-tv,genreRomance,genreSci-fi,genreShort,genreSport,genreThriller,genreWar,genreWestern
0,0,0,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62290,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
62291,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
62292,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
62293,0,0,0,0,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
62294,1,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [16]:
genre_columns = [col for col in genres.columns if col.startswith('genre')]
column_names = [col.replace('genre', '') for col in genre_columns]
print(f"All {len(column_names)} unique movie genres/categories: ", column_names)

All 28 unique movie genres/categories:  ['Action', 'Adult', 'Adventure', 'Animation', 'Biography', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film-noir', 'History', 'Horror', 'Imax', 'Music', 'Musical', 'Mystery', 'News', 'Reality-tv', 'Romance', 'Sci-fi', 'Short', 'Sport', 'Thriller', 'War', 'Western']

In [17]:
movies_with_context = pd.concat([movies_with_context, genres], axis=1)
movies_with_context = movies_with_context.drop(columns=['genres'])
movies_with_context

,movieId,title,movieYear,titleType,isAdult,runtimeMinutes,directors,actor,genreAction,genreAdult,...,genreMystery,genreNews,genreReality-tv,genreRomance,genreSci-fi,genreShort,genreSport,genreThriller,genreWar,genreWestern
0,1,Toy Story (1995),1995,movie,0,81,nm0005124,nm0000741,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),1995,movie,0,104,nm0002653,nm0001372,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),1995,movie,0,101,nm0222043,nm0025908,0,0,...,0,0,0,1,0,0,0,0,0,0
3,4,Waiting to Exhale (1995),1995,movie,0,124,nm0001845,nm0001365,0,0,...,0,0,0,1,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),1995,movie,0,106,nm0796124,nm0003028,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62290,209157,We (2018),2018,movie,0,100,nm1415482,nm10312234,0,0,...,0,0,0,0,0,0,0,0,0,0
62291,209159,Window of the Soul (2001),2001,movie,0,73,nm0142504,nm1546270,0,0,...,0,0,0,0,0,0,0,0,0,0
62292,209163,Bad Poems (2018),2018,movie,0,97,nm2520391,nm0468514,0,0,...,0,0,0,0,0,0,0,0,0,0
62293,209169,A Girl Thing (2001),2001,tvMovie,0,237,nm0003022,nm0121700,0,0,...,0,0,0,1,0,0,0,0,0,0
62294,209171,Women of Devil's Island (1962),1962,movie,0,86,nm0659992,nm0033980,1,0,...,0,0,0,0,0,0,0,0,0,0

Replace '\N' values in column directors with 'no_director'

In [27]:
print('Number of \"\\N\" values in column directors: ', len(movies_with_context[movies_with_context['directors'] == '\\N']))
movies_with_context['directors'] = movies_with_context['directors'].replace('\\N', 'no_director')
print('Number of \"\\N\" values in column directors: ', len(movies_with_context[movies_with_context['directors'] == '\\N']))

Number of "\N" values in column directors:  165
Number of "\N" values in column directors:  0

Replace '\N' values in column runtimeMinutes with 0 and convert the column to int

In [28]:
print('Number of \"\\N\" values in column runtimeMinutes: ', len(movies_with_context[movies_with_context['runtimeMinutes'] == '\\N']))
movies_with_context['runtimeMinutes'] = movies_with_context['runtimeMinutes'].replace('\\N', '0')
print('Number of \"\\N\" values in column runtimeMinutes: ', len(movies_with_context[movies_with_context['directors'] == '\\N']))

movies_with_context['runtimeMinutes'] = movies_with_context['runtimeMinutes'].astype(int)

Number of "\N" values in column runtimeMinutes:  191
Number of "\N" values in column runtimeMinutes:  0

---

In [32]:
movies_with_context.to_csv(file_depth + new_context_path + 'movies_with_context.csv', index=False)