In [1]:
import pandas as pd
# import numpy as np
# import json
# import os

In [2]:

# datasets needed to create the final dataset (they are not present in the /recommender repository)
movies_with_context_path = 'data/movies_with_context.csv'
added_imdb_context_path = 'data/added_imdb_context_with_ratings.csv'


data_path = 'data/'
recsys_movies_context_data_path = 'data/recsys_movies_context_data.csv'

In [4]:
movies_with_context = pd.read_csv(movies_with_context_path)
movies_with_context

,movieId,title,movieYear,titleType,isAdult,runtimeMinutes,directors,actor,genreAction,genreAdult,...,genreMystery,genreNews,genreReality-tv,genreRomance,genreSci-fi,genreShort,genreSport,genreThriller,genreWar,genreWestern
0,1,Toy Story (1995),1995,movie,0,81,nm0005124,nm0000741,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),1995,movie,0,104,nm0002653,nm0001372,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),1995,movie,0,101,nm0222043,nm0025908,0,0,...,0,0,0,1,0,0,0,0,0,0
3,4,Waiting to Exhale (1995),1995,movie,0,124,nm0001845,nm0001365,0,0,...,0,0,0,1,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),1995,movie,0,106,nm0796124,nm0003028,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58918,209157,We (2018),2018,movie,0,100,nm1415482,nm10312234,0,0,...,0,0,0,0,0,0,0,0,0,0
58919,209159,Window of the Soul (2001),2001,movie,0,73,nm0142504,nm1546270,0,0,...,0,0,0,0,0,0,0,0,0,0
58920,209163,Bad Poems (2018),2018,movie,0,97,nm2520391,nm0468514,0,0,...,0,0,0,0,0,0,0,0,0,0
58921,209169,A Girl Thing (2001),2001,tvMovie,0,237,nm0003022,nm0121700,0,0,...,0,0,0,1,0,0,0,0,0,0
58922,209171,Women of Devil's Island (1962),1962,movie,0,86,nm0659992,nm0033980,1,0,...,0,0,0,0,0,0,0,0,0,0

Drop title from movie context data

In [5]:
recsys_movies_context = movies_with_context.drop('title', axis=1)
recsys_movies_context.to_csv(data_path + 'recsys_movies_context_data.csv', index=False)
recsys_movies_context

,movieId,movieYear,titleType,isAdult,runtimeMinutes,directors,actor,genreAction,genreAdult,genreAdventure,...,genreMystery,genreNews,genreReality-tv,genreRomance,genreSci-fi,genreShort,genreSport,genreThriller,genreWar,genreWestern
0,1,1995,movie,0,81,nm0005124,nm0000741,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,2,1995,movie,0,104,nm0002653,nm0001372,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,1995,movie,0,101,nm0222043,nm0025908,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,4,1995,movie,0,124,nm0001845,nm0001365,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,5,1995,movie,0,106,nm0796124,nm0003028,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58918,209157,2018,movie,0,100,nm1415482,nm10312234,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58919,209159,2001,movie,0,73,nm0142504,nm1546270,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58920,209163,2018,movie,0,97,nm2520391,nm0468514,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58921,209169,2001,tvMovie,0,237,nm0003022,nm0121700,0,0,0,...,0,0,0,1,0,0,0,0,0,0
58922,209171,1962,movie,0,86,nm0659992,nm0033980,1,0,1,...,0,0,0,0,0,0,0,0,0,0

Create dataframe from ratings with only userId and movieId

In [3]:
added_imdb_context = pd.read_csv(added_imdb_context_path)
added_imdb_context

,userId,movieId,day,isWeekday,season,partOfDay,holiday,movieYear,titleType,isAdult,...,genreNews,genreReality-tv,genreRomance,genreSci-fi,genreShort,genreSport,genreThriller,genreWar,genreWestern,rating
0,1,296,3,1,1,3,no_holiday,1994,movie,0,...,0,0,0,0,0,0,1,0,0,5.0
1,1,306,3,1,1,2,no_holiday,1994,movie,0,...,0,0,0,0,0,0,0,0,0,3.5
2,1,307,3,1,1,2,no_holiday,1993,movie,0,...,0,0,0,0,0,0,0,0,0,5.0
3,1,665,3,1,1,3,no_holiday,1995,movie,0,...,0,0,0,0,0,0,0,1,0,5.0
4,1,899,3,1,1,2,no_holiday,1952,movie,0,...,0,0,1,0,0,0,0,0,0,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24983464,162541,50872,2,1,1,4,no_holiday,2007,movie,0,...,0,0,0,0,0,0,0,0,0,4.5
24983465,162541,55768,2,1,1,4,no_holiday,2007,movie,0,...,0,0,0,0,0,0,0,0,0,2.5
24983466,162541,56176,2,1,1,4,no_holiday,2007,movie,0,...,0,0,0,0,0,0,0,0,0,2.0
24983467,162541,58559,2,1,1,4,no_holiday,2008,movie,0,...,0,0,0,0,0,0,0,0,0,4.0
24983468,162541,63876,2,1,1,4,no_holiday,2008,movie,0,...,0,0,0,0,0,0,0,0,0,5.0

Keep only userId and movieId

In [5]:
recsys_ratings_user_movie = added_imdb_context[['userId', 'movieId']]
recsys_ratings_user_movie.to_csv(data_path + 'recsys_ratings_only_userid_movieid.csv', index=False)
recsys_ratings_user_movie

          userId  movieId
0              1      296
1              1      306
2              1      307
3              1      665
4              1      899
...          ...      ...
24983464  162541    50872
24983465  162541    55768
24983466  162541    56176
24983467  162541    58559
24983468  162541    63876

[24983469 rows x 2 columns]